# Generated by Django 3.2.8 on 2023-05-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svoy01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='svoy01.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to='', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
    ]
